[opener]
edit = [
    { run = 'nvim %s', block = true, for = "unix" },
]
open_dir = [
    { run = 'nvim %d1', block = true, for = "unix" },
]
play = [
	{ run = 'mpv %s', orphan = true, desc = "MPV" }
]
image = [
    { run = 'qview %s', orphan = true, desc = "qView image viewer"}
]

[open]
rules = [
    { url = "*.txt", use = "edit" },
	{ url = "*.md",  use = "edit" },
	{ url = "*.mp3",  use = "play" },
	{ mime = "video/*", use = "play" },
	{ mime = "image/*", use = "image" },
	{ mime = "audio/*", use = "play" },
    { url = "*", use = [ "edit", "open_dir" ] },
]
