[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Neovim" }
]
play = [
    { run = 'mpv "$@"', block = true, desc = "MPV Player" }
]
web = [
    {run = 'barve "$@"', orphan = true, desc = "open in brave browser"}
]

[open]
prepend_rules = [
    { url = "*.json", use = "edit" },
    
    { mime = "video/*", use = "play" },
    
    { url = "*.html", use = [ "open", "edit" ] }
]
