#!/bin/bash
mod=Mod4

. "$HOME/.config/river/auto_start"

riverctl map normal ${mod}+Shift r "$HOME/.config/river/auto_start"

riverctl map normal $mod b spawn qutebrowser
riverctl map normal $mod e spawn nemo
riverctl map normal $mod d spawn "bemenu-run -p 'run' -l 10 --fn 'Roman[15]'"
riverctl map normal ${mod}+Alt p spawn swaylock
riverctl map normal Control+Shift 1 spawn 'wayshot -g'
riverctl map normal Control+Shift 2 spawn "wayshot && notify-send 'capture whole screen'"
riverctl map normal $mod Return spawn foot 
riverctl map normal ${mod}+Shift e exit

riverctl map normal $mod q close

riverctl map normal $mod j focus-view next
riverctl map normal $mod k focus-view previous

riverctl map normal $mod h send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal $mod l send-layout-cmd rivercarro "main-ratio +0.05"

riverctl map normal ${mod}+Shift j swap next
riverctl map normal ${mod}+Shift k swap previous

riverctl map normal ${mod} Period focus-output next
riverctl map normal ${mod} Comma focus-output previous

riverctl map normal ${mod}+Shift Period send-to-output next
riverctl map normal ${mod}+Shift Comma send-to-output previous

riverctl map normal $mod z zoom

# $mod+Alt+{H,J,K,L} to move views
riverctl map normal ${mod}+Alt H move left 50
riverctl map normal ${mod}+Alt J move down 50
riverctl map normal ${mod}+Alt K move up 50
riverctl map normal ${mod}+Alt L move right 50

# $mod+Alt+Control+{H,J,K,L} to snap views to screen edges 
# float Windows only
riverctl map normal ${mod}+Alt+Control H snap left
riverctl map normal ${mod}+Alt+Control J snap down
riverctl map normal ${mod}+Alt+Control K snap up
riverctl map normal ${mod}+Alt+Control L snap right

# $mod+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal ${mod}+Alt+Shift H resize horizontal -100
riverctl map normal ${mod}+Alt+Shift J resize vertical 100
riverctl map normal ${mod}+Alt+Shift K resize vertical -100
riverctl map normal ${mod}+Alt+Shift L resize horizontal 100

# $mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# $mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# $mod + Middle Mouse Button to toggle float
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal ${mod}+Shift $i set-view-tags $tags
    riverctl map normal ${mod}+Control $i toggle-focused-tags $tags
    riverctl map normal ${mod}+Shift+Control $i toggle-view-tags $tags
done

# $mod+0 to focus all tags
# $mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal ${mod}+Shift 0 set-view-tags $all_tags

riverctl map normal $mod Space toggle-float
riverctl map normal $mod f toggle-fullscreen


# ------------------------------------------------------------------------------------------
# resize Windows

# $mod+Shift+H and $mod+Shift+L to increment/decrement the main count of rivercarro(1)
# $mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal $mod Right send-layout-cmd rivercarro "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivercarro "main-location left"

riverctl map normal $mod w     send-layout-cmd rivercarro "main-location-cycle left,monocle"
# ------------------------------------------------------------------------------------------


# Add others rivercarro's commands the same way with the keybinds you'd like.
# e.g.
# riverctl map normal $mod <keys> send-layout-cmd rivercarro "inner-gaps -1"
# riverctl map normal $mod <keys> send-layout-cmd rivercarro "inner-gaps +1"
# riverctl map normal $mod <keys> send-layout-cmd rivercarro "outer-gaps -1"
# riverctl map normal $mod <keys> send-layout-cmd rivercarro "outer-gaps +1"
# riverctl map normal $mod <keys> send-layout-cmd rivercarro "width-ratio -0.1"
# riverctl map normal $mod <keys> send-layout-cmd rivercarro "width-ratio +0.1"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# $mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# $mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

riverctl hide-cursor timeout 3000
riverctl hide-cursor when-typing enabled

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl border-color-focused  0x00ff00
riverctl border-color-unfocused 0x000000ff
riverctl border-width 2

riverctl set-repeat 30 300
riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl rule-add -app-id "bar" csd
riverctl rule-add -app-id "*" ssd
riverctl rule-add -app-id 'org.qutebrowser.qutebrowser' tags $((1 << 1))
riverctl rule-add -app-id 'wechat' tags $((1 << 2))
riverctl rule-add -app-id 'QQ' tags $((1 << 2))

riverctl default-layout rivercarro
rivercarro -outer-gaps 0 -per-tag &
