# ~/.config/river/rrwm.toml

[input.keyboard]
layout = "us"
variant = "qwerty" # Defaults to qwerty
options = "caps:swapescape" # Supports multiple options, separated by commas
model = "pc105" # Defaults to pc105
numlock = "true" # Defaults to false

[waybar] # Configure tag icons here; defaults to Arabic numerals
tag_icons = ["", "", "󰃽", "", "", "󰙯", "", "󰎄", "", "", "", "󰊴", "", "", "󰆍", "", "", "", "", "󰘦", "", "󰗨"]
focused_style = "<span color='#bd93f9'>" # Style for focused tags
occupied_style = "<span color='#6C7086'>" # Style for unfocused/occupied tags
empty_style = "<span color='#313244'>" # Style for empty tags

# Use `wev` to find XKB names for specific keys
[keybindings.alt]
# (spawn has lower overhead, but cannot access user environment variables)
j = { action="shell", cmd='/usr/bin/grim -g "$(/usr/bin/slurp < /dev/null)" - | /usr/bin/satty --filename -' }
a = { action="spawn", args=["/usr/bin/fuzzel", "toggle"] }

# Support for different modifiers
[keybindings.super]
Return = { action = "spawn", args = ["foot"] }
q = { action = "close_focused" }
# Toggle full screen
f = { action = "toggle_fullscreen" }
# Switch focus between different tags
1 = { action = "focus", args = ["1"] }
2 = { action = "focus", args = ["2"] }
3 = { action = "focus", args = ["3"] }
4 = { action = "focus", args = ["4"] }
5 = { action = "focus", args = ["5"] }
6 = { action = "focus", args = ["6"] }
7 = { action = "focus", args = ["7"] }
8 = { action = "focus", args = ["8"] }
9 = { action = "focus", args = ["9"] }
0 = { action = "focus", args = ["31"] }
# Focus movement (Up/Down/Left/Right), automatically crossing tag boundaries
n = { action = "focus", args = ["left"] }
i = { action = "focus", args = ["right"] }
u = { action = "focus", args = ["up"] }
e = { action = "focus", args = ["down"] }

# Example of multiple modifiers: Alt + Shift
[keybindings.alt_shift]
# Reload configuration 
# (Hot-plugging monitors might cause waybar overlap; restarting waybar helps)
c = [
    { action = "reload_configuration" },
    { action = "spawn", args = ["pkill", "waybar"] },
    { action = "shell", cmd = "sleep 0.1;waybar &" },
]
# Move window to another tag
1 = { action = "move", args = ["1"] }
# ...
0 = { action = "move", args = ["10"] }
# Move window (Up/Down/Left/Right), automatically crossing tag boundaries
n = { action = "move", args = ["left"] }
i = { action = "move", args = ["right"] }
u = { action = "move", args = ["up"] }
e = { action = "move", args = ["down"] }

# Use quotes if you want to use the plus sign for multiple modifiers
[keybindings."super+shift"]
space = { action = "spawn", args = ["rofi"] }

# Keys without modifiers
[keybindings]
F1 = { action = "shell", cmd = "pactl set-sink-volume @DEFAULT_SINK@ -5%" }
[keybindings.none]
F2 = { action = "shell", cmd = "pactl set-sink-volume @DEFAULT_SINK@ +5%" }

# Switch focus between multiple outputs (monitors)
[keybindings.alt_ctrl]
u = { action = "focus", args = ["up_output"] }
e = { action = "focus", args = ["down_output"] }
n = { action = "focus", args = ["left_output"] }
i = { action = "focus", args = ["right_output"] }

# Move window between multiple outputs
[keybindings.alt_ctrl_shift]
u = { action = "move", args = ["up_output"] }
e = { action = "move", args = ["down_output"] }
n = { action = "move", args = ["left_output"] }
i = { action = "move", args = ["right_output"] }

[window]
smart_borders = "true" # Hide borders/gaps when only one window is present
gaps = "2" # Gap between windows

[window.active] # Borders for focused window
border = { width = "2", color = "#bd93f9" }

[window.rule] # The icons configured for the software can be dynamically displayed in the tag
match = [
	{ appid="kitty", icon="" },
	{ appid="neovim", icon="" },
	{ appid="wechat", icon="" },
]
