#!/bin/env sh

cpu() {
	cpu="$(grep -o "^[^ ]*" /proc/loadavg)"
}

memory() {
	memory="$(free -h | sed -n "2s/\([^ ]* *\)\{2\}\([^ ]*\).*/\2/p")"
}

disk() {
    disk="$(df -h | grep -E "/\$" | grep -o "[0-9]\+%")"
}

datetime() {
    datetime="$(date -u +"%A %Y-%m-%d %H:%M")"
}

bat() {
    bat="$(upower -b | grep -E "percentage" | grep -o  "[0-9]\+%")"
}

vol() {
	vol="$([ "$(pamixer --get-mute)" = "false" ] && printf "%s%%" "$(pamixer --get-volume)" || printf '-')"
}

sunrise() {
    sunrise="$(curl -s 'https://api.met.no/weatherapi/sunrise/3.0/sun?lat=22.2769&lon=113.5678&offset=+08:00' | grep -oP '"sunrise":{"time":"[^"]*T\K\d{2}:\d{2}' )"
}

sunset() {
    sunset="$(curl -s 'https://api.met.no/weatherapi/sunrise/3.0/sun?lat=22.2769&lon=113.5678&offset=+08:00' | grep -oP '"sunset":{"time":"[^"]*T\K\d{2}:\d{2}' )"
}
solarmidnight() {
    solarmidnight="$(curl -s 'https://api.met.no/weatherapi/sunrise/3.0/sun?lat=22.2769&lon=113.5678&offset=+08:00' | grep -oP '"solarmidnight":{"time":"[^"]*T\K\d{2}:\d{2}' )"
}
solarnoon() {
    solarnoon="$(curl -s 'https://api.met.no/weatherapi/sunrise/3.0/sun?lat=22.2769&lon=113.5678&offset=+08:00' | grep -oP '"solarnoon":{"time":"[^"]*T\K\d{2}:\d{2}' )"
}

display() {
	echo "all status [🌅 $sunrise ☀️ $solarnoon 🌇 $sunset ⏳ $solarmidnight] [💾 $memory] [💻 $cpu] [💽 $disk] [🔋 $bat] [🔉 $vol] [$datetime]" >"$FIFO"
}


printf "%s" "$$" > "$XDG_RUNTIME_DIR/status_pid"
FIFO="$XDG_RUNTIME_DIR/sandbar"
[ -e "$FIFO" ] || mkfifo "$FIFO"
sec=0

while true; do
	sleep 1 &
	wait && {
		[ $((sec % 36000)) -eq 0 ] && sunrise
		[ $((sec % 36000)) -eq 0 ] && solarnoon
		[ $((sec % 36000)) -eq 0 ] && sunset
		[ $((sec % 36000)) -eq 0 ] && solarmidnight
		[ $((sec % 15)) -eq 0 ] && memory
		[ $((sec % 15)) -eq 0 ] && cpu
		[ $((sec % 15)) -eq 0 ] && disk
		[ $((sec % 60)) -eq 0 ] && bat
		[ $((sec % 5)) -eq 0 ] && vol
		[ $((sec % 5)) -eq 0 ] && datetime

		[ $((sec % 5)) -eq 0 ] && display

		sec=$((sec + 1))
	}
done
